name: Periodically Update Schemas

on:
  schedule:
    - cron: "45 5 * * 1"
  workflow_dispatch:

jobs:
  update-schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Schemas
        run: ./scripts/updateSchemas.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
